### PR TITLE
Allow entering value outside min max range for numeric input 

### PR DESCRIPTION
**Pull request by WeirdRubberDuck**
https://github.com/OpenSpace/OpenSpace/issues/2449

Shows invalid value in red and outside of min/max range in yellow. For both NumericInput and MinMaxRangeInput

Behavior for minMaxRange can be considered a little weird, as there is only one tooltip for two inputs. But, I did not want to overcomplicate that code. Hopefully, it's good enough. Example of what I mean shown in video below. At least both of the values share the same min and max range

https://user-images.githubusercontent.com/8808894/229716043-c8aba698-6916-4a5d-85d5-998787d8de8f.mov

### CODE REVIEW

**Comment by WeirdRubberDuck** [comment]
@ylvaselling Just for knowledge, I plan to rewrite both these components as functional components. That would hopefully simplify the code a bit. 

However, did not want to do it as part of this PR

**Comment by alexanderbock** [comment]
Little inconsistency [example based on `Opacity` property:
1. Press "." which changes `1` to `1.0`
2. Press "." again, which clears the field without showing the "This is not a valid number error"
3. Press "." again, which enters ".0" which is a valid number
image

Second case:
Same steps as before but:
0. Enter -1, turning the dialog yellow for outside of range
after step 3 the field says ".0" but with the error
image

Third case:
1. Remove the existing number, turning the dialog red
2. Press "." which adds ".0" but written in red
image

**Comment by alexanderbock** [comment]
Impressive that `1e0` is a valid input for range [0,1] :+1:

**Review by ylvaselling — APPROVED** [review]
I think it looks good! 

I had one thought (that I don't think is very important): I didn't really understand why the component uses the <Input> component in some cases and the <input> in others

**Comment by WeirdRubberDuck** [comment]
> I think it looks good!
> 
> I had one thought (that I don't think is very important): I didn't really understand why the component uses the component in some cases and the in others

Know now that you're talking about `<Input>` VS `<input>` ;) 

We use `<Input>` for text-based input (in this case, numeric), and `<input>` for creating the different custom sliders for the NumericInput and MinMaxRangeInput components. 

All three components, `Input`, `NumericInput` and `MinMaxRangeInput` are really only customized versions of the `<input>` tag

**Comment by WeirdRubberDuck** [comment]
> Little inconsistency [example based on `Opacity` property:
> 
> 1. Press "." which changes `1` to `1.0`
> 2. Press "." again, which clears the field without showing the "This is not a valid number error"
> 3. Press "." again, which enters ".0" which is a valid number
>    image
> 
> Second case: Same steps as before but: 0. Enter -1, turning the dialog yellow for outside of range after step 3 the field says ".0" but with the error image
> 
> Third case:
> 
> 1. Remove the existing number, turning the dialog red
> 2. Press "." which adds ".0" but written in red
>    image

Good find @alexanderbock ! Should be fixed now.

This .0 thing still really bugs me. Long term, we should really consider using text input instead of number inputs, and doing the input handling for numbers ourselves. Could potentially fix quite a few problems for us

**Pull request merged**
