### PR TITLE
Add search to actions panel

### PR DESCRIPTION
**Pull request by ylvaselling**
This PR adds a search to the Actions panel as well as the actions window route. 

Note: there is a bug in this PR which is fixed in the GeoPosition panel PR. The bus is that currently when you clear the search field, it doesn't work.

### CODE REVIEW

**Review by WeirdRubberDuck — CHANGES_REQUESTED** [review]
Code looks great IMO, but clearing the search field does not reset the shown actions correctly when on the top level and other levels that include folders. This should be fixed 

Expected behavior would be "no search" == "show all"

https://user-images.githubusercontent.com/8808894/185852972-65e57aa1-795d-4bab-8b17-ef3345912ec1.mov

**Comment by WeirdRubberDuck** [comment]
Ans a suggestion on a stylistic change, to make the panel less crowded: Howe about moving the "back" button to the same row as the folder path? It would be nice to give some more room to the actions in the panel, especially with the search field addition. Thoughts? 

image

**Comment by ylvaselling** [comment]
> Code looks great IMO, but clearing the search field does not reset the shown actions correctly when on the top level and other levels that include folders. This should be fixed
> 
> Expected behavior would be "no search" == "show all"
> 
>  2022-08-22.08-23-18.mov

This is a bug that is fixed in the geoposition panel so I think I will wait for that to be merged and then merge in master in this PR

**Comment by ylvaselling** [comment]
> Ans a suggestion on a stylistic change, to make the panel less crowded: Howe about moving the "back" button to the same row as the folder path? It would be nice to give some more room to the actions in the panel, especially with the search field addition. Thoughts?
> 
> image

I think it makes sense to have them on the same row, only problem i can think of is if the path becomes too long... then what do we do? Truncate the beginning with ...? 🤔 I guess another nice-to-have is to be able to click on the path to go to a folder but I'm not sure if that's worth the trouble to make

**Comment by WeirdRubberDuck** [comment]
> > Ans a suggestion on a stylistic change, to make the panel less crowded: Howe about moving the "back" button to the same row as the folder path? It would be nice to give some more room to the actions in the panel, especially with the search field addition. Thoughts?
> > image
> 
> I think it makes sense to have them on the same row, only problem i can think of is if the path becomes too long... then what do we do? Truncate the beginning with ...? 🤔 I guess another nice-to-have is to be able to click on the path to go to a folder but I'm not sure if that's worth the trouble to make

Truncating the beginning of the path sounds good enough to me, if it's even a problem. At least right now we don't have very deep folder structures (and it would be inconvenient because of all the "back clicks" needed to go back to the top)

Clicking the path to go to a folder (similar to the Windows file system) would indeed be a nice to have, if we want to make it easier for users to have deep folder trees. However, IMO the search functionality reduces the need to subdivide all the actions into folders, so I think that can be left as a future work :) Maybe make an issue that captures the idea

**Comment by WeirdRubberDuck** [comment]
> > Code looks great IMO, but clearing the search field does not reset the shown actions correctly when on the top level and other levels that include folders. This should be fixed
> > Expected behavior would be "no search" == "show all"
> > 2022-08-22.08-23-18.mov
> 
> This is a bug that is fixed in the geoposition panel so I think I will wait for that to be merged and then merge in master in this PR

Great!

**Review by alexanderbock — APPROVED** [review]
Looks awesome and works great :)

**Pull request merged**
