### PR TITLE
Issue #2174 - Nodes without GUI tag does not show in scene menu

### PR DESCRIPTION
**Pull request by WeirdRubberDuck**
Show scene graph nodes without group at the top level of the UI

### CODE REVIEW

**Comment by alexanderbock** [comment]
We could set the hidden flag on the Root now in the Scene constructor (https://github.com/OpenSpace/OpenSpace/blob/master/src/scene/scene.cpp#L118-L119)?

How much work would it be to align them?

**Comment by WeirdRubberDuck** [comment]
> We could set the hidden flag on the Root now in the Scene constructor (https://github.com/OpenSpace/OpenSpace/blob/master/src/scene/scene.cpp#L118-L119)?
> 
> How much work would it be to align them?

As we discussed during the meeting, I'll skip aligning them, as we probably want to redesign this in the future and the majority of nodes that will be shown will likely be mistakes (from the user forgetting to including the GUI tag in the asset)

And regarding setting the properties of the Scene node, it's unfortunately not that simple 🥲  We send another property owner to the UI, and for some reason that does not properly send all the properties of the scene graph node.  Have to spend some more time investigating how it works and why https://github.com/OpenSpace/OpenSpace/blob/5ec67f8226d106e8a9553eb8bb125d8a29257b85/modules/server/src/topics/getpropertytopic.cpp#L70

**Comment by alexanderbock** [comment]
Maybe an invalid test, but if i run this branch against current `master` (_not_ the updated PR), when I open the Scene menu I get:

```
[0327/103008.611:INFO:CONSOLE(75158)] "Warning: validateDOMNesting(...): %s cannot appear as a descendant of <%s>.%s <button> button
    at button
    at http://127.0.0.1:4690/frontend/static/bundle.js:35901:81
    at Checkbox (http://127.0.0.1:4690/frontend/static/bundle.js:35978:22)
    at span
    at div
    at div
    at http://127.0.0.1:4690/frontend/static/bundle.js:37951:99
    at button
    at http://127.0.0.1:4690/frontend/static/bundle.js:35901:81
    at PropertyOwnerHeader (http://127.0.0.1:4690/frontend/static/bundle.js:31583:23)
    at div
    at ToggleContent (http://127.0.0.1:4690/frontend/static/bundle.js:38290:26)
    at PropertyOwner (http://127.0.0.1:4690/frontend/static/bundle.js:31283:18)
    at ContextSection (http://127.0.0.1:4690/frontend/static/bundle.js:30398:34)
    at div
    at ScrollOverlay (http://127.0.0.1:4690/frontend/static/bundle.js:38000:24)
    at FilterListFavorites (http://127.0.0.1:4690/frontend/static/bundle.js:35549:25)
    at div
    at FilterList (http://127.0.0.1:4690/frontend/static/bundle.js:35655:23)
    at div
    at section
    at Pane (http://127.0.0.1:4690/frontend/static/bundle.js:30645:23)
    at ScenePane (http://127.0.0.1:4690/frontend/static/bundle.js:32294:28)
    at section
    at div
    at Resizable (http://127.0.0.1:4690/frontend/static/bundle.js:66737:28)
    at Sidebar (http://127.0.0.1:4690/frontend/static/bundle.js:32724:27)
    at section
    at RefsProvider (http://127.0.0.1:4690/frontend/static/bundle.js:28618:51)
    at div
    at OnScreenGui (http://127.0.0.1:4690/frontend/static/bundle.js:39968:26)
    at RenderedRoute (http://127.0.0.1:4690/frontend/static/bundle.js:137390:5)
    at Routes (http://127.0.0.1:4690/frontend/static/bundle.js:138011:5)
    at Router (http://127.0.0.1:4690/frontend/static/bundle.js:137949:15)
    at HashRouter (http://127.0.0.1:4690/frontend/static/bundle.js:136050:5)
    at App
    at Provider (http://127.0.0.1:4690/frontend/static/bundle.js:130209:20)", source: http://127.0.0.1:4690/frontend/static/bundle.js (75158)
```

**Comment by WeirdRubberDuck** [comment]
> When run this branch against current `master` and the updated PR, when I open the Scene menu I get:
> 
> ```
> [0327/103008.611:INFO:CONSOLE(75158)] "Warning: validateDOMNesting(...): %s cannot appear as a descendant of <%s>.%s <button> button
>     at button
>     at http://127.0.0.1:4690/frontend/static/bundle.js:35901:81
>     at Checkbox (http://127.0.0.1:4690/frontend/static/bundle.js:35978:22)
>     at span
>     at div
>     at div
>     at http://127.0.0.1:4690/frontend/static/bundle.js:37951:99
>     at button
>     at http://127.0.0.1:4690/frontend/static/bundle.js:35901:81
>     at PropertyOwnerHeader (http://127.0.0.1:4690/frontend/static/bundle.js:31583:23)
>     at div
>     at ToggleContent (http://127.0.0.1:4690/frontend/static/bundle.js:38290:26)
>     at PropertyOwner (http://127.0.0.1:4690/frontend/static/bundle.js:31283:18)
>     at ContextSection (http://127.0.0.1:4690/frontend/static/bundle.js:30398:34)
>     at div
>     at ScrollOverlay (http://127.0.0.1:4690/frontend/static/bundle.js:38000:24)
>     at FilterListFavorites (http://127.0.0.1:4690/frontend/static/bundle.js:35549:25)
>     at div
>     at FilterList (http://127.0.0.1:4690/frontend/static/bundle.js:35655:23)
>     at div
>     at section
>     at Pane (http://127.0.0.1:4690/frontend/static/bundle.js:30645:23)
>     at ScenePane (http://127.0.0.1:4690/frontend/static/bundle.js:32294:28)
>     at section
>     at div
>     at Resizable (http://127.0.0.1:4690/frontend/static/bundle.js:66737:28)
>     at Sidebar (http://127.0.0.1:4690/frontend/static/bundle.js:32724:27)
>     at section
>     at RefsProvider (http://127.0.0.1:4690/frontend/static/bundle.js:28618:51)
>     at div
>     at OnScreenGui (http://127.0.0.1:4690/frontend/static/bundle.js:39968:26)
>     at RenderedRoute (http://127.0.0.1:4690/frontend/static/bundle.js:137390:5)
>     at Routes (http://127.0.0.1:4690/frontend/static/bundle.js:138011:5)
>     at Router (http://127.0.0.1:4690/frontend/static/bundle.js:137949:15)
>     at HashRouter (http://127.0.0.1:4690/frontend/static/bundle.js:136050:5)
>     at App
>     at Provider (http://127.0.0.1:4690/frontend/static/bundle.js:130209:20)", source: http://127.0.0.1:4690/frontend/static/bundle.js (75158)
> ```

Have seen this too, but it's not a problem with this PR specifically - it's from the scene menu (or any propertyownerheader) and shows anytime we run the development GUI.  As the error message says it has to do with the fact that we have buttons within other buttons

Don't think this warning shows when running the production GUI?  Have to verufy that though.  

Either way, not related to this PR, it exists in master too

**Pull request merged**
