### PR TITLE
Issue/2665 - Show timer for how long time left in camera path

### PR DESCRIPTION
**Pull request by WeirdRubberDuck**
Also show which scene graph node the camera is flying to, instead of the current anchor node

Closes OpenSpace/OpenSpace#2665

Related to OpenSpace PR: https://github.com/OpenSpace/OpenSpace/pull/2980

Adds a special topic for the camera paths. I first considered including the information together with the other camera topic, but that topic sends information about the updated camera position **constantly** when subscribed to. To only get updates when a camera path is playing, it was better to use a separate topic

Attached a demo video in the core slack, but here it is again

https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/assets/8808894/4604c2eb-4634-4e07-863f-bf2a4a1e5999

### CODE REVIEW

**Comment by alexanderbock** [comment]
The Cancel and anchor text has a different font from the rest, but maybe that is expected?

image

**Comment by alexanderbock** [comment]
I'd also say that the "button-ness" of the cancel could be a bit more obvious?  It's pretty subltly brighter

**Comment by alexanderbock** [comment]
Last, based on your final commit, I think for me, the second countdown is not synched with the blinking, but it's also not super important to me

https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/assets/4921724/6e0f308c-330b-4206-a199-443eb6b82355

**Comment by WeirdRubberDuck** [comment]
> Last, based on your final commit, I think for me, the second countdown is not synched with the blinking, but it's also not super important to me
> 
>  2023-12-15.16-29-42.mp4

Hard to see anything in that video :)  And my thought was not to have it completely in sync, but 2 seconds felt a bit better than 1.5 seconds for me personally.

**Comment by WeirdRubberDuck** [comment]
> The Cancel and anchor text has a different font from the rest, but maybe that is expected?
> 
> image

Wow, that's very observant of you :)  No, not expected in my opinion.  But as per usual, our CSS is a bit messy so I'm not sure why the font is different. Have to investigate

**Comment by WeirdRubberDuck** [comment]
@alexanderbock the font on the button is the same that is used for other buttons (and in some other places as well) across the page.  Changing it will lead to a lot of visual changes across the entire UI, so I'll leave it for now. Seems like we use two different fonts in the webpage in general

Regarding the "button-ness", I made the background a bit brighter both on default and on hover.  This affects all the other buttons in the UI as well, but I think the increased contrast is mainly a good thing. In particular, the session recording buttons now look the same as this one for the origin picker: 
image

**Comment by WeirdRubberDuck** [comment]
Although, note that I now need to update the hover behavior for a lot of other things across the UI... It is apparently a 50% change as to whether a clickable thing in the UI uses the button CSS or not... 😢 😬 

Notice the difference in shade on hover of (seemingly) equal items in the video below... this is the result of the button color change

https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/assets/8808894/eab66940-fe36-4f34-a727-d0e622ae6b79

**Pull request merged**
