### PR TITLE
Feature/more focus options

### PR DESCRIPTION
**Pull request by WeirdRubberDuck**
Make it so that the navigation button is always visible (more touch friendly), and expose some extra buttons and settings in a "..."-menu.  

Note that the "settings" in this menu is just a quick access to the properties.  Thoughts on that? Does a user understand that this is the case?

Looking for input on the design of the menu, the choice of settings, and also how a similar menu could look in the "..." of the scene graph nodes in the Scene pane :) 

closes https://github.com/OpenSpace/OpenSpace/issues/2925

image

### CODE REVIEW

**Comment by WeirdRubberDuck** [comment]
Demo video 
https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/assets/8808894/dcdcb089-913f-4bfb-aa6f-9b7a36019b87

**Comment by alexanderbock** [comment]
- Do we need the "Fly to" if we do have the airplane button in the list already?
 - Would be nice lookswise to have the ... menu take less space horizontally?

**Comment by WeirdRubberDuck** [comment]
Updated looks: 
image

**Comment by alexanderbock** [comment]
The callout error is not vertically aligned with the center of the "..."

**Comment by WeirdRubberDuck** [comment]
> The callout error is not vertically aligned with the center of the "..."

I knooow...! Positioning is hard 🥲 

But sure, I'll give it another look

**Comment by alexanderbock** [comment]
Definitely not a blocker!  If it is very hard to do, we can ust merge

**Pull request merged**
