### PR TITLE
Feature/enhance getting started tour

### PR DESCRIPTION
**Pull request by ylvaselling**
This PR fixes a couple of bugs regarding the getting started tour:

1. Click indicator can point to the wrong thing
2. Click indicator stays when popup is closed
3. Click indicator can make content bounce up and down in the menus when they are at bottom
4. Popup slide is placed on top of the altitude 
5. Unclear phrasing about the Moon as a planet

There are also some enhancements:
1. Supports two click indicators at the same time, making it more clear where to click
2. Allows user to click either Sweden or Utah for layers
3. Adds geo position panel to the slides

Will close:
https://github.com/OpenSpace/OpenSpace/issues/2277
https://github.com/OpenSpace/OpenSpace/issues/2233

### CODE REVIEW

**Comment by Roxeena** [comment]
I can still get the issue that the indicator is placed in the wrong place. For the task to change the color of Mars’s trail, if I open Earth's trail item in the menu it then points to Earth's trail color instead of Mars’s trail color. Same if I open Venus or Mercury trails too, it picks the one that is furthest up in the list.

**Comment by alexanderbock** [comment]
While doing the tour and going to the correct long,lat coordinates the "Success" screen seems uncompleted:
image

**Comment by alexanderbock** [comment]
When changing the trail color of Mars, I had to change all three RGB values at least once before it let me continue, but I was expecting it to work if either any one of R, G, _or_ B.  Maybe the text should mention that

**Comment by alexanderbock** [comment]
"All the default layers in OpenSpace are named after the satellite that captured the map" -> "All the default layers in OpenSpace are usually named after the satellite or an instrument on a satellite that captured the map"

**Comment by alexanderbock** [comment]
image

in the title of the panel it is called "Geo Location"

**Pull request merged**
